-- Generated by Matugen

local colors = {
	active_border = "rgba({{colors.primary.default.hex_stripped}}ff)",
	inactive_border = "rgba({{colors.surface_container_high.default.hex_stripped}}cc)",
	urgent_border = "rgba({{colors.error.default.hex_stripped}}ff)",
	shadow = "rgba({{colors.shadow.default.hex_stripped}}77)",
}
return colors
