color0 #111319
color1 #ffb4ab
color2 #a8c8ff
color3 #b2c7f0
color4 #f2afff
color5 #a8c8ff
color6 #b2c7f0
color7 #e1e2ea
color8 #8b919d
color9 #ffb4ab
color10 #a8c8ff
color11 #b2c7f0
color12 #f2afff
color13 #a8c8ff
color14 #b2c7f0
color15 #e1e2ea

cursor                #e1e2ea
cursor_text_color     #111319
background            #111319
foreground            #e1e2ea
selection_foreground  #c1c6d4
selection_background  #414752
active_border_color   #a8c8ff
inactive_border_color #414752
url_color             #a8c8ff

active_tab_foreground   #003062
active_tab_background   #a8c8ff
inactive_tab_foreground #c1c6d4
inactive_tab_background #414752
cursor_trail_color      #c1c6d4
