
background #111318
foreground #e1e2e9

color0  #111318
color1  #ffb4ab
color2  #a8c8ff
color3  #bdc7dc
color4  #dbbce1
color5  #a8c8ff
color6  #bdc7dc
color7  #e1e2e9

color8  #43474e
color15 #e1e2e9
