cursor            #e6c26c
cursor_text_color #3e2e00

foreground            #eae1d4
background            #110e07
selection_foreground  #3a2f15
selection_background  #d6c5a0
url_color             #d6c5a0

#: black 000000 767676
color0  #17130b
color8  #39342b
#: red cc0403 f2201f
color1  #e88252
color9  #fae4d9
#: green 19cb00 23fd00
color2  #d6c5a0
color10 #f3e1bb
#: yellow cecb00 fffd00
color3  #afcfab
color11 #caebc6
#: blue 0d73cc 1a8fff
color4  #5a4400
color12 #e6c26c
#: magenta cb1ed1 fd28ff
color5  #51452a
color13 #d6c5a0
#: cyan 0dcdcd 14ffff
color6  #314d32
color14 #afcfab
#: white dddddd ffffff
color7  #d0c5b4
color15 #eae1d4

mark1_foreground #251a00
mark1_background #ffdf97
mark2_foreground #231a04
mark2_background #f3e1bb
mark3_foreground #05210a
mark3_background #caebc6

active_tab_foreground #3e2e00
active_tab_background #e6c26c
inactive_tab_foreground #ffdf97
inactive_tab_background #5a4400

active_border_color #e6c26c
inactive_border_color #3e2e00
# bell_border_color #ff5a00
