theme {
  color_scheme = /home/san/.config/hypr/colors/qt6_colors_schema.conf
  icon_theme = Papirus-Dark
  style = kvantum-dark
  font_fixed = JetBrainsMono Nerd Font
  font_fixed_size = 10
  font = Google Sans
  font_size = 10
}
