"$schema" = 'https://starship.rs/config-schema.json'
palette = "noctalia"

format = """
$directory\
$git_branch\
$git_status\
$character"""

right_format = "$cmd_duration"

add_newline = false
command_timeout = 500

[directory]
home_symbol = "~"
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = true

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"
truncation_length = 24
truncation_symbol = "..."
disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bold yellow"
conflicted = "󰕚 "
untracked = "? "
modified = "! "
staged = "+ "
renamed = "» "
deleted = "✘ "
stashed = "$ "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕ "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "bold yellow"
disabled = false














# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (wallpaper-based)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#a8c8ff"
red       = "#ffb4ab"
green     = "#bdc7dc"
yellow    = "#dbbce1"
cyan      = "#bdc7dc"
magenta   = "#a8c8ff"
white     = "#e3e2e6"
black     = "#121316"

# Extended palette (Catppuccin-compatible names)
rosewater = "#dbbce1"
flamingo  = "#dbbce1"
pink      = "#a8c8ff"
mauve     = "#245fa6"
maroon    = "#ffb4ab"
peach     = "#dbbce1"
teal      = "#bdc7dc"
sky       = "#bdc7dc"
sapphire  = "#bdc7dc"
lavender  = "#245fa6"

# Text shades
text      = "#e3e2e6"
subtext1  = "#c4c6cf"
subtext0  = "#8e9199"

# Surface shades
overlay2  = "#8e9199"
overlay1  = "#c4c6cf"
overlay0  = "#43474e"
surface2  = "#43474e"
surface1  = "#121316"
surface0  = "#121316"
base      = "#121316"
mantle    = "#121316"
crust     = "#3e2845"
# <<< NOCTALIA STARSHIP PALETTE <<<
