source=./bind.conf
source=./noctalia.conf

# Configuration
#
# Environmet Variables
env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=QT_QPA_PLATFORM,Wayland;xcb
env=QT_QPA_PLATFORMTHEME,qt6ct

# Autostart
exec-once=noctalia

# Input
# keyboard Settings
repeat_rate=25
repeat_delay=250
numlockon=0
xkb_rules_layout=us

# Miscellaneous
# focus & input
cursor_hide_on_keypress=1
drag_tile_to_tile=1
drag_corner=4
# window behavior
enable_floating_snap=1
snap_distance=30


# Visuals
#
# Theming
# dimensions
borderpx=1
gappih=2
gappiv=2
gappoh=4
gappov=4
# cursor theme
cursor_theme = Bibata-Modern-Classic
cursor_size=20

# Window Effects
# blur
blur=0
blur_layer=1
blur_params_radius=5
blur_params_num_passes=2
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1.0
# shadows
shadows=1
layer_shadows=0
shadows_size=4
shadows_blur=12
shadows_position_x=2
shadows_position_y=2
# opacity & corner radius
border_radius=2
focused_opacity=0.95
unfocused_opacity=0.8
# animation
animations=1
layer_animations=0
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1
zoom_initial_ratio=0.4
zoom_end_ratio=0.8
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.8
animation_duration_move=150
animation_duration_open=200
animation_duration_tag=150
animation_duration_close=400
animation_duration_focus=0
animation_curve_open=0.46,1.0,0.29,1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_close=0.08,0.92,0,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opafadeout=0.5,0.5,0.5,0.5
animation_curve_opafadein=0.46,1.0,0.29,1


# Window Management
#
# Layouts
# supported layouts
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:fair
tagrule=id:4,layout_name:grid
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:deck
tagrule=id:7,layout_name:right_tile
tagrule=id:8,layout_name:vertical_tile
tagrule=id:9,layout_name:center_tile
# scroller layout
scroller_default_proportion=0.5
scroller_proportion_preset=0.5,0.8,1.0
scroller_default_proportion_single=1.0
# master-stack layouts
default_mfact=0.5
# dwindle layout
# none


# Rules
#
# window rules
windowrule=isfloating:1,width:0.8,height:0.8,appid:dev.noctalia.Noctalia
windowrule=isfloating:1,width:0.5,height:0.5,appid:com.saivert.pwvucontrol
windowrule=isfloating:1,width:0.5,height:0.5,appid:org.pulseaudio.pavucontrol
windowrule=isfloating:1,width:0.8,height:0.8,appid:imv


# Overview
#
# overview settings
enable_hotarea=1


# Scratchpad
#
# none
