# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x121314ff
bordercolor = 0x8c9195ff
dropcolor = 0xb0cadb80
splitcolor = 0xd8bedbff
focuscolor = 0xb0cadbff
maximizescreencolor = 0xbec8cfff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd8bedbff
globalcolor = 0x7e98a8ff
overlaycolor = 0x414a51ff
jump_label_decorate_fg_color = 0xe3e2e3ff
jump_label_decorate_bg_color = 0x292a2bff
jump_label_decorate_focus_fg_color = 0x193341ff
jump_label_decorate_focus_bg_color = 0xb0cadbff
jump_label_decorate_border_color = 0x8c9195ff
group_bar_decorate_fg_color = 0xe3e2e3ff
group_bar_decorate_bg_color = 0x292a2bff
group_bar_decorate_focus_fg_color = 0x193341ff
group_bar_decorate_focus_bg_color = 0xb0cadbff
group_bar_decorate_border_color = 0x8c9195ff
