[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/san/.cache/noctalia/placeholder.json"

[templates.hyprland]
input_path = "~/.config/noctalia/templates/hyprland.lua"
output_path = "~/.config/hypr/colors/hyprland_colors.lua"

[templates.hyprtoolkit]
input_path = "~/.config/noctalia/templates/hyprtoolkit.conf"
output_path = "~/.config/hypr/hyprtoolkit.conf"

[templates.hyprqt6engine]
input_path = "~/.config/noctalia/templates/hyprqt6engine.conf"
output_path = "~/.config/hypr/colors/hyprqt6engine_colors.conf"

[templates.kvantum_kvconfig]
input_path = "~/.config/noctalia/templates/kvantum.kvconfig"
output_path = "~/.config/Kvantum/noctalia/noctalia.kvconfig"

[templates.kvantum_svg]
input_path = "~/.config/noctalia/templates/kvantum.svg"
output_path = "~/.config/Kvantum/noctalia/noctalia.svg"

[templates.prismlauncher]
input_path = "~/.config/noctalia/templates/prismlauncher.json"
output_path = "~/.local/share/FreesmLauncher/themes/noctalia/theme.json"
